name: pre-merge-checks
run-name: ${{ github.actor }} is checking your code consistency
on:
  pull:
    branches: [main, develop]
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run start_check
      - run: npm run check
      - run: npm run finish_check
